# Workflow file for github actions
name: Run tests (ubuntu)

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  test:
    env:
      PY_COLORS: 1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          pip install -r requirements.txt
      - name: Check the console scripts interface
        run: |
          seleniumbase
      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver
      - name: Install pyautogui
        run: |
          python -m pip install pyautogui
          sudo apt-get install -y python3-tk
          sudo apt-get install -y python3-dev
      - name: Make sure pytest is working
        run: |
          echo "def test_1(): pass" > test_1.py
          pytest test_1.py
      - name: Run tests
        run: |
          pytest tests/sumAssertion.py
      - name: Run app
        run: |
          python main.py